--[[
  Atomic Guild Creation — debits Mana, allocates a guild_id, and writes
  every related hash/set in one block. Phase 9c / fix #21.

  The previous flow was: debit_mana_lua (atomic) → INCR counter → 5
  separate HSET/SADD operations. A failure between the debit and the
  rest left the user with no guild and no Mana refund — the
  idempotency_key was already consumed by debit_mana_lua, so retries
  returned DUPLICATE_REQUEST.

  KEYS[1] = game:state:{user_id}
  KEYS[2] = game:guild_id_counter   (string, INCR'd)
  ARGV[1] = creation_cost_mana
  ARGV[2] = guild_name
  ARGV[3] = invite_code             (pre-generated by Python)
  ARGV[4] = idempotency_key
  ARGV[5] = world_boss_hp           (initial HP from master_config)
  ARGV[6] = user_id                 (string)
  ARGV[7] = current_time_unix       (string)

  Returns: { new_mana_balance, new_guild_id }
    Or `{err = "DUPLICATE_REQUEST"}` on retry.
    Or `{err = "INSUFFICIENT_MANA"}` if balance < cost.

  Note: keys constructed dynamically inside Lua (game:guild:{id} etc.) are
  not declared in KEYS, which makes this script single-node-only. The
  current docker-compose deployment is single-node Redis; if we ever move
  to Cluster, these keys need to use a hash tag like {user_id} to ensure
  same-slot routing.
--]]

local state_key      = KEYS[1]
local counter_key    = KEYS[2]
local cost           = tonumber(ARGV[1])
local guild_name     = ARGV[2]
local invite_code    = ARGV[3]
local idem_key       = ARGV[4]
local boss_hp        = ARGV[5]
local user_id        = ARGV[6]
local now            = ARGV[7]
local processed_key  = "game:processed_txns"

if redis.call("SADD", processed_key, idem_key) == 0 then
    return {err = "DUPLICATE_REQUEST"}
end

local balance = tonumber(redis.call("HGET", state_key, "mana_balance") or "0")
if balance < cost then
    redis.call("SREM", processed_key, idem_key)
    return {err = "INSUFFICIENT_MANA"}
end

local new_balance = redis.call("HINCRBY", state_key, "mana_balance", -cost)
local guild_id = redis.call("INCR", counter_key)
local guild_id_str = tostring(guild_id)

local guild_key = "game:guild:" .. guild_id_str
redis.call("HSET", guild_key,
    "name", guild_name,
    "invite_code", invite_code,
    "guildmaster_user_id", user_id,
    "boss_hp_remaining", boss_hp,
    "created_at", now
)
redis.call("SET", "game:invite:" .. invite_code, guild_id_str)
redis.call("SADD", "game:guild:" .. guild_id_str .. ":roster", user_id)
redis.call("HSET", "game:guild:" .. guild_id_str .. ":roles", user_id, "guildmaster")
redis.call("HSET", state_key, "guild_id", guild_id_str)
redis.call("HSET", "game:last_seen", user_id, now)

return {new_balance, guild_id}
